services:
  ai-karaoke:
    build: .
    image: rune-encoder/ai-karaoke-studio
    environment:
      ACOUST_ID: OPrpWW9ZVS
      GENIUS_API_ACCESS_TOKEN: Mi774TCiZopyf9flNeuJJjklgcIoWi2AM7dM0zRjSm51Wg-J0XC_dFcllFUKM2zm
      GEMINI_API_KEY: AIzaSyAj04oiDMaV4Zr8ib_qiMQc9V7zSqrcgmc
    ports:
      - 7860:7860
    volumes:
      - ./cache:/app/cache:rw
      - ./fonts:/app/fonts:ro
      - ./effects:/app/effects:ro
      - ./logs:/app/logs:rw
      - ./output:/app/output:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
